# Generated by Django 5.0.14 on 2026-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_contactmessage_appointment_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='landing_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='show_on_landing',
            field=models.BooleanField(default=False),
        ),
    ]
